name: just-build

on:
  # Manual trigger for rollback to specific release or redeploy latest
  workflow_dispatch:

env:
  M4U_WEB_REPO: ${{ github.repository }} # mathforyou/M4u.Web

  IMAGE_NAME: 'ghcr.io/mathforyou/m4u-web' # ghcr.io/mathforyou/m4u-web
  DOCKER_FILE_PATH: 'build/m4u-web.Dockerfile'

  NUGET_USERNAME: 'mathforyou'
  NUGET_PASSWORD: ${{ secrets.GITHUB_TOKEN }}
  # NUGET_SOURCE: https://nuget.pkg.github.com/mathforyou/index.json

  # envs from runtime
  # IMAGE_LATEST_TAG: ghcr.io/mathforyou/m4u-web:latest

jobs:
  build-image:
    runs-on: ubuntu-22.04

    permissions:
      contents: read
      packages: write

    steps:
      # clone M4u.Web repo from current tag
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          repository: ${{ env.M4U_WEB_REPO }}
          ref: ${{ github.ref_name }}

      - name: Create docker image tags
        id: tags
        run: |
          echo "IMAGE_LATEST_TAG=${{ env.IMAGE_NAME }}:latest" >> $GITHUB_ENV

      - name: Create NuGet source
        run: |
          echo "NUGET_SOURCE=https://nuget.pkg.github.com/${{ env.NUGET_USERNAME }}/index.json" >> $GITHUB_ENV

      - name: Print runtime environment variables
        run: |
          echo "IMAGE_LATEST_TAG=${{ env.IMAGE_LATEST_TAG }}"
          echo "NUGET_SOURCE=${{ env.NUGET_SOURCE }}"

      # =======================================================

      - name: Just Build WITHOUT Push!
        uses: docker/build-push-action@v5
        with:
          # не пушим в артифактори, а просто билдим
          push: false
          file: ${{ env.DOCKER_FILE_PATH }}
          build-args: |
            NUGET_SOURCE=${{ env.NUGET_SOURCE }}
            NUGET_USERNAME=${{ env.NUGET_USERNAME }}
            NUGET_PASSWORD=${{ env.NUGET_PASSWORD }}
          tags: ${{ env.IMAGE_LATEST_TAG }}
          context: .